name: nurse
on: workflow_dispatch
jobs:
    getserviceversions:
      runs-on: ubuntu-latest
      
      steps:
      - name: GitVersion
        run: |
              git version
              mvn --version

    getimage:
      runs-on: ubuntu-latest

      needs: getserviceversions
      steps:
       - name: pullmySQLImg
         run: |
               docker pull mysql
               docker --version
               docker run -d --name mcon -e 'MYSQL_ROOT_PASSWORD=1234' mysql
    
